server {
    listen 80;
    server_name your-domain.com ec2-public-ip;

    location /static/ {
        alias /home/ubuntu/social_media_api/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/social_media_api/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/social_media_api/social_media_api.sock;
    }
}
